

final garages = [
      {
        'name': 'Balaji Automobiles',
        'id': 'D252SS4P585S4F',
        'phone': '1234567890',
        'type': 'CAR',
        'iconPath': 'assets/icons/mechanic.png',
        'distance': '220.0m',
        'time': '9am - 9pm',
        'address': 'H-30 4th Floor Laxmi Nagar Near Sai Baba Mandir Gokalpuri , Lodi Colony, New Delhi 110093 India.',
      },
      {
        'name': 'V K Motors Garage',
        'id': 'L192SS4P587S54F',
        'phone': '1234567890',
        'type': 'CAR',
        'iconPath': 'assets/icons/mechanic.png',
        'distance': '800.0m',
        'time': '8am - 9pm',
        'address': '23/3, Chinchwad, Road, Pune, Maharashtra India.',
      },
      {
        'name': 'Speed Auto Care',
        'id': 'Z952SS4M585S4Z',
        'phone': '1234567890',
        'type': 'CAR',
        'iconPath': 'assets/icons/mechanic.png',
        'distance': '1.2km',
        'time': '9am - 6pm',
        'address': '44, MG Road, Sector 14, Gurugram, Haryana, India.',
      },
      {
        'name': 'Pragati Motors',
        'id': 'D252SS4P585S4F',
        'phone': '1234567890',
        'type': 'BIKE',
        'iconPath': 'assets/icons/mechanic.png',
        'distance': '150.0m',
        'time': '10am - 8pm',
        'address': 'Plot No. 12, Sector 5, Near Metro Station, Noida, India.',
      },
      {
        'name': 'Ride On Garage',
        'id': 'B842BB2Q999X7H',
        'phone': '1234567890',
        'type': 'BIKE',
        'iconPath': 'assets/icons/mechanic.png',
        'distance': '500.0m',
        'time': '7am - 9pm',
        'address': 'Lane 4, Baner, Pune, Maharashtra, India.',
      },
    ];